var drawWall=function(a){a.fillStyle="rgb(150, 150, 150)";a.fillRect(312,550,400,50)},drawText=function(a,c){$(a).html(c)},drawMap=function(){},createContext=function(a){return a.getContext?a.getContext("2d"):!1},mouseHandler=function(a){$(a).mousedown(function(a){self.goons.push(createGoon(a.pageX,a.pageY,Math.round(360*Math.random()),4,1,1));for(var b in self.goons){var d=self.goons[b];1==d.alive&&d.addCommand("face",40,a.pageX,a.pageY)}});$(a).mousemove(function(){self.active=!0});window.addEventListener("devicemotion",
function(a){var b=Math.round(100*a.accelerationIncludingGravity.x)/100,d=Math.round(100*a.accelerationIncludingGravity.y)/100;drawText(self.txtdiv,b+" "+d+" int: "+a.interval)},!0)},mainloop=function(){if(1E4<this.active)this.clearInterval(this.interval),confirm("Are you still there?")&&(this.interval=this.setInterval("mainloop()",this.intervalAmount),this.active=0);else{this.active++;for(var a in this.mapTiles){var c=this.mapTiles[a];c.updateFlag&&(this.ctx.clearRect(c.x1,c.y1,this.tileWidth,this.tileHeight),
c.draw(this.ctx),c.updateFlag=!1)}drawWall(this.ctx);this.ctx.fillStyle="rgb(255, 0, 0)";this.ctx.fillRect(512,300,2,2);for(var b in this.goons)a=this.goons[b],1==a.alive&&(a.render(this.ctx,this.spriteSet),processGoons(a))}},createGoon=function(a,c,b,d,e,f){a={x:a,y:c,degrees:b,speed:d,alive:e,frame:f,radius:50,id:self.globalGoonCount,happiness:0,turndirection:"",turncount:0,consecutiveturn:0,command:"move",commandLength:0,commandQueue:[],ignoreGoons:0,leniency:30,turn:function(){36<this.consecutiveturn&&
(this.leniency-=2);this.turncount>3*this.consecutiveturn&&(this.turndirection="left"==this.turndirection?"right":"left",this.turncount=0);"right"==this.turndirection?this.incrementdegrees(10):"left"==this.turndirection?this.incrementdegrees(-10):this.turndirection=0.5>Math.random()?"left":"right";this.turncount++;this.consecutiveturn++},face:function(a,c){var b=0;if(a==this.x)b=c==this.y?this.degrees:c>this.y?180:0;else if(c==this.y)b=a>this.x?270:90;else{var d=Math.abs(a-this.x),e=Math.abs(c-this.y);
a<this.x&&c>this.y?b=RadDeg(Math.atan(d/e)):a<this.x&&c<this.y?b=RadDeg(Math.atan(e/d))+90:a>this.x&&c<this.y?b=270-RadDeg(Math.atan(e/d)):a>this.x&&c>this.y&&(b=360-RadDeg(Math.atan(d/e)))}b=alterdegrees(b,0);angledifference(alterdegrees(this.degrees,10),b)<angledifference(alterdegrees(this.degrees,-10),b)?10<angledifference(alterdegrees(this.degrees,10),b)?this.incrementdegrees(10):this.degrees=b:10<angledifference(alterdegrees(this.degrees,-10),b)?this.incrementdegrees(-10):this.degrees=b;return this.degrees==
b},move:function(a,b){this.x-=a;this.y+=b;this.consecutiveturn=0;this.leniency=30;for(var c in self.triggerAreas){var d=self.triggerAreas[c];if((Math.abs(d.x-this.x)-30>=d.r?d.r:Math.abs(d.y-this.y)-30>=d.r?d.r:calcDist(this.x,this.y,d.x,d.y)-30)<d.r){d.updateFlag=!0;switch(d.command){default:(this.goal_x!=d.trigger.x||this.goal_y!=d.trigger.y&&"face"!=this.command)&&this.addCommand("face",40,d.trigger.x,d.trigger.y)}break}}},incrementdegrees:function(a){this.degrees+=a;0>this.degrees?this.degrees+=
360:360<=this.degrees&&(this.degrees-=360)},addCommand:function(a,b,c,d){this.commandQueue.unshift({command:a,commandLength:b,x:c,y:d})},pathCollides:function(a,b,c){var a=this.x-a,b=this.y+b,d=this.id;if(50>a||a>self.canvasWidth-50||50>b||b>self.canvasHeight-50)return!0;var e=!1;if(!1==c)for(var f in self.goons){var g=self.goons[f];if(g.id!=d){var c=Math.abs(g.x-a),j=Math.abs(g.y-b);c>=this.leniency||j>=this.leniency||(c=calcDist(g.x,g.y,a,b),c<this.leniency&&(e=!0));if(!0==e)break}}if(!e)for(f in d=
this.leniency,self.obstacles)if(g=self.obstacles[f],c=Math.abs(g.x-a)-g.r,j=Math.abs(g.y-b)-g.r,c>=d||j>=d||(c=calcDist(g.x,g.y,a,b),c<d+g.r&&(e=!0)),!0==e)break;return e},informCollision:function(a,b){var c=this.x-a,d=this.y+b,e;for(e in self.goons){var f=self.goons[e];f.x!=this.x&&f.y!=this.y&&calcDist(f.x,f.y,c,d)>this.leniency&&(f.addCommand("wait",200,-1,-1),console.log("waitCount set"))}},render:function(a,b){DegRad(this.degrees);b[this.frame]?a.drawImage(b[this.frame],this.x-25,this.y-25):
console.log("invalid: "+this.frame)}};self.globalGoonCount++;return a},createObstacle=function(a,c,b){return{x:a,y:c,r:b,draw:function(a){a.fillStyle="rgb(255, 0, 0)";a.fillRect(this.x,this.y,1,1);a.beginPath();a.arc(this.x,this.y,this.r,DegRad(0),DegRad(359),!1);a.lineWidth=1;a.strokeStyle="black";a.closePath();a.stroke()}}},createTrigger=function(a,c,b,d){a={x:a,y:c,r:b,trigger:d,id:self.globalTriggerCount,draw:function(a){a.fillStyle="rgb(255, 0, 0)";a.fillRect(this.x,this.y,1,1);a.beginPath();
a.arc(this.x,this.y,this.r,DegRad(0),DegRad(359),!1);a.lineWidth=1;a.strokeStyle="blue";a.closePath();a.stroke()}};self.globalTriggerCount++;return a},createSpawnZone=function(a,c,b){a={x:a,y:c,r:b,x1:a-b,y1:c-b,x2:a+b,y2:c+b,id:self.globalSpawnZoneCount,draw:function(a){a.fillStyle="rgba(20, 30, 255, 0.2)";a.beginPath();a.arc(this.x,this.y,this.r,DegRad(0),DegRad(359),!1);a.closePath();a.fill()},pointIn:function(a,b){return calcdist(a,b,this.x,this.y)<=this.r?!0:!1}};self.globalSpawnZoneCount++;
return a},createTile=function(a,c,b,d){var e=this,a={id:e.globalTileCount,updateFlag:!0,x1:a,y1:c,x2:b,y2:d,draw:function(){e.tileImages[this.id]||console.log(this.id)},pointIn:function(a,b){return a>=this.x1&&a<this.x2&&b>=this.y1&&b<this.y2?!0:!1}};e.globalTileCount++;return a},RadDeg=function(a){return 180*a/Math.PI},DegRad=function(a){return a*Math.PI/180},angledifference=function(a,c){var b=Math.abs(c-a);180<b&&(b=360-b);return b},alterdegrees=function(a,c){var b=a+c;if(360<=b)b%=360;else if(0>
b)for(;0>b;)b+=360;return b},calcDist=function(a,c,b,d){a=b-a;c=d-c;return Math.sqrt(a*a+c*c)},posConflict=function(a,c){var b=!1;if(50>a||a>self.canvasWidth-50||50>c||c>self.canvasHeight-50)b=!0;if(!b)for(var d in self.goons){var e=self.goons[d],f=Math.abs(a-e.x),h=Math.abs(c-e.y);f>=e.leniency||h>=e.leniency||(f=Math.sqrt(f*f+h*h),f<e.leniency&&(b=!0));if(!0==b)break}if(!b)for(d in self.obstacles)if(e=self.obstacles[d],f=Math.abs(a-e.x),h=Math.abs(c-e.y),f>=60+e.r||h>=60+e.r||(f=calcDist(e.x,e.y,
a,c)-e.r,f<60+e.r&&(b=!0)),!0==b)break;return b},processGoons=function(a){if(0<a.commandLength&&"move"!=a.command){if("face"==a.command)a.face(a.goal_x,a.goal_y)?a.commandLength=0:a.face(a.goal_x,a.goal_y);else if("attack"!=a.command&&"wait"!=a.command&&"stepBack"==a.command){var c=-Math.round(Math.sin(DegRad(a.degrees))*a.speed/2),b=-Math.round(Math.cos(DegRad(a.degrees))*a.speed/2);a.pathCollides(c,b,0<a.ignoreGoons,a.leniency)?a.turn():a.move(c,b);a.frame=(a.frame+1)%24}a.commandLength--}else 0<
a.commandQueue.length?(c=a.commandQueue.pop(),a.command=c.command,a.commandLength=c.commandLength,0<c.x&&0<c.y&&(a.goal_x=c.x,a.goal_y=c.y)):a.addCommand("move",0,-1,-1),"move"==a.command&&(c=Math.round(Math.sin(DegRad(a.degrees))*a.speed/2),b=Math.round(Math.cos(DegRad(a.degrees))*a.speed/2),a.pathCollides(c,b,0<a.ignoreGoons,a.leniency)?a.turn():a.move(c,b),0<a.ignoreGoons&&a.ignoreGoons--,a.frame=(a.frame+1)%24);affectArea(a.x,a.y)},affectArea=function(a,c){var b=a+50,d=a-50,e=c+50,f=c-50,h;for(h in this.mapTiles){var i=
this.mapTiles[h];if(i.pointIn(b,e)||i.pointIn(b,f)||i.pointIn(d,e)||i.pointIn(d,f))i.updateFlag=!0}},run=function(){mouseHandler(this.canvas);drawMap(this.ctx);this.interval=this.setInterval("mainloop()",this.intervalAmount)},dBoom=function(){this.canvas=document.getElementById("dCanvas");this.txtdiv=document.getElementById("dTextDiv");this.ctx=createContext(this.canvas);this.spriteSet=[];this.active=0;this.intervalAmount=70;this.canvasWidth=800;this.canvasHeight=500;for(var a=this.globalTileCount=
this.globalSpawnZoneCount=this.globalTriggerCount=this.globalGoonCount=0;24>a;a++)this.spriteSet[a]=new Image,this.spriteSet[a].src="img/skeleton_archer/s_a_move_torso_00"+(5>a?"0":"")+2*a+".png";this.goons=[];this.obstacles=[];this.triggerAreas=[];this.spawnZones=[];this.mapTiles=[];this.tileHeight=this.tileWidth=100;this.tileImages=[];for(a=1;40>=a;a++){var c=new Image;c.src="img/map_tiles/map_tile_"+(10>a?"0":"")+a+".jpg";var b=100*((a-1)%8),d=100*Math.floor((a-1)/8);this.mapTiles.push(createTile(b,
d,b+99,d+99));this.tileImages.push(c)}this.obstacles.push(createObstacle(289,297,40));this.obstacles.push(createObstacle(304,262,39));this.obstacles.push(createObstacle(313,186,36));this.obstacles.push(createObstacle(288,119,37));this.obstacles.push(createObstacle(263,77,45));this.obstacles.push(createObstacle(300,153,38));this.obstacles.push(createObstacle(312,30,40));this.obstacles.push(createObstacle(308,227,36));this.obstacles.push(createObstacle(360,8,25));this.obstacles.push(createObstacle(40,
193,60));this.obstacles.push(createObstacle(22,262,57));this.obstacles.push(createObstacle(7,581,55));this.obstacles.push(createObstacle(562,163,41));this.obstacles.push(createObstacle(522,197,23));this.obstacles.push(createObstacle(645,151,55));this.obstacles.push(createObstacle(687,91,55));this.obstacles.push(createObstacle(674,219,35));this.obstacles.push(createObstacle(682,27,27));this.obstacles.push(createObstacle(968,387,68));this.obstacles.push(createObstacle(998,279,45));this.obstacles.push(createObstacle(963,
488,72));this.obstacles.push(createObstacle(956,591,95));this.obstacles.push(createObstacle(1012,225,50));this.triggerAreas.push(createTrigger(51,70,20,{command:"face",x:132,y:57}));this.triggerAreas.push(createTrigger(172,65,20,{command:"face",x:177,y:191}));this.triggerAreas.push(createTrigger(177,191,40,{command:"face",x:137,y:404}));this.triggerAreas.push(createTrigger(137,404,25,{command:"face",x:317,y:550}));this.triggerAreas.push(createTrigger(859,0,85,{command:"face",x:797,y:332}));this.triggerAreas.push(createTrigger(868,
159,25,{command:"face",x:797,y:332}));this.triggerAreas.push(createTrigger(742,147,15,{command:"face",x:797,y:332}));this.triggerAreas.push(createTrigger(797,332,25,{command:"face",x:625,y:306}));this.spawnZones.push(createSpawnZone(115,81,60));this.spawnZones.push(createSpawnZone(477,63,70));c=this.spawnZones[Math.floor(Math.random()*this.spawnZones.length)];for(a=0;10>a;a++){for(var b=Math.round(2*Math.random()*c.r)+c.x1,d=Math.round(2*Math.random()*c.r)+c.y1,e=Math.round(359*Math.random()),f=Math.round(23*
Math.random()),h=!1,i=0;!h&&24>i;)b=Math.round(2*Math.random()*c.r)+c.x1,d=Math.round(2*Math.random()*c.r)+c.y1,h=!posConflict(b,d),i++;24<=i||this.goons.push(createGoon(b,d,e,3,1,f))}setTimeout("run()",3E3)};window.onload=function(){dBoom()};